import 'modals/product_modal.dart';

class global {
  static bool data = false;
  static List<Product> products = [
    Product(
      id: 1,
      name: "Avocado Salad",
      price: 20.0,
      image: "assets/images/Avocado_Salad.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 2,
      name: "Monsoon Salad",
      price: 15.0,
      image: "assets/images/Monsoon_Salad.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 3,
      name: "Royal Salad",
      price: 25.0,
      image: "assets/images/Royal_Salad.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 4,
      name: "Fruits Salad",
      price: 10.0,
      image: "assets/images/Fruits_Salad.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 5,
      name: "Loyal Salad",
      price: 28.0,
      image: "assets/images/Loyal_Salad.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 6,
      name: "Basic Salad",
      price: 10.0,
      image: "assets/images/Basic_Salad.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 7,
      name: "All Fruits",
      price: 23.0,
      image: "assets/images/All_Fruits.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 8,
      name: "Mi Fruits",
      price: 29.0,
      image: "assets/images/Mi_Fruits.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 9,
      name: "Unique Fruits",
      price: 40.0,
      image: "assets/images/Unique_Fruits.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 10,
      name: "All Grocery",
      price: 100.0,
      image: "assets/images/All_Grocery.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 11,
      name: "Mix Grocery",
      price: 120.0,
      image: "assets/images/Mix_Grocery.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 12,
      name: "Basic Grocery",
      price: 150.0,
      image: "assets/images/Basic_Grocery.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 13,
      name: "Crude Grocery",
      price: 220.0,
      image: "assets/images/Crude_Grocery.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 14,
      name: "All Veges",
      price: 420.0,
      image: "assets/images/All_Veges.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 15,
      name: "Mix Veges",
      price: 580.0,
      image: "assets/images/Mix_Veges.png",
      quantity: 0,
      like: "false",
    ),
  ];
}